# -*- coding: utf-8 -*-
"""Gabarito Tipos de Variáveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BV7ZtROLiE5dOSJH97e7dZb0xK3Hfwd2
"""

faturamento = 2000
custo = 500
lucro = faturamento - custo

print('O faturamento da loja foi ' + str(faturamento) + '.O custo da loja foi ' + str(custo) + '.Assim, o lucro da loja foi de ' + str(lucro))